# Generated by Django 4.2.2 on 2023-06-06 21:25

from django.db import migrations, models
import django.db.models.deletion
import manageSystem_app.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(blank=True, default=manageSystem_app.models.get_datetime, verbose_name='created')),
                ('modified', models.DateTimeField(blank=True, default=manageSystem_app.models.get_datetime, verbose_name='modified')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
            ],
            options={
                'verbose_name': 'dish',
                'verbose_name_plural': 'dishes',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(blank=True, default=manageSystem_app.models.get_datetime, verbose_name='created')),
                ('modified', models.DateTimeField(blank=True, default=manageSystem_app.models.get_datetime, verbose_name='modified')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
            ],
            options={
                'verbose_name': 'menu',
                'verbose_name_plural': 'menus',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(blank=True, default=manageSystem_app.models.get_datetime, verbose_name='created')),
            ],
            options={
                'verbose_name': 'order',
                'verbose_name_plural': 'orders',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(blank=True, default=manageSystem_app.models.get_datetime, verbose_name='created')),
                ('modified', models.DateTimeField(blank=True, default=manageSystem_app.models.get_datetime, verbose_name='modified')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('address', models.CharField(max_length=255, verbose_name='address')),
            ],
            options={
                'verbose_name': 'supplier',
                'verbose_name_plural': 'suppliers',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(blank=True, default=manageSystem_app.models.get_datetime, verbose_name='created')),
                ('number', models.IntegerField(verbose_name='number')),
                ('capacity', models.PositiveIntegerField(verbose_name='capacity')),
            ],
            options={
                'verbose_name': 'table',
                'verbose_name_plural': 'tables',
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='OrderDish',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(blank=True, default=manageSystem_app.models.get_datetime, verbose_name='created')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='quantity')),
                ('dish', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='manageSystem_app.dish')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='manageSystem_app.order')),
            ],
            options={
                'unique_together': {('order', 'dish')},
            },
        ),
        migrations.AddField(
            model_name='order',
            name='dishes',
            field=models.ManyToManyField(through='manageSystem_app.OrderDish', to='manageSystem_app.dish', verbose_name='dishes'),
        ),
        migrations.AddField(
            model_name='order',
            name='table',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='manageSystem_app.table'),
        ),
        migrations.CreateModel(
            name='MenuDish',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(blank=True, default=manageSystem_app.models.get_datetime, verbose_name='created')),
                ('dish', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='manageSystem_app.dish')),
                ('menu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='manageSystem_app.menu')),
            ],
            options={
                'unique_together': {('menu', 'dish')},
            },
        ),
        migrations.AddField(
            model_name='menu',
            name='dishes',
            field=models.ManyToManyField(through='manageSystem_app.MenuDish', to='manageSystem_app.dish', verbose_name='dishes'),
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(blank=True, default=manageSystem_app.models.get_datetime, verbose_name='created')),
                ('modified', models.DateTimeField(blank=True, default=manageSystem_app.models.get_datetime, verbose_name='modified')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='quantity')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='manageSystem_app.supplier')),
            ],
            options={
                'verbose_name': 'ingredient',
                'verbose_name_plural': 'ingredients',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DishIngredient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(blank=True, default=manageSystem_app.models.get_datetime, verbose_name='created')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='quantity')),
                ('dish', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='manageSystem_app.dish')),
                ('ingredient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='manageSystem_app.ingredient')),
            ],
            options={
                'unique_together': {('dish', 'ingredient')},
            },
        ),
        migrations.AddField(
            model_name='dish',
            name='ingredients',
            field=models.ManyToManyField(through='manageSystem_app.DishIngredient', to='manageSystem_app.ingredient', verbose_name='ingredients'),
        ),
    ]
