# Generated by Django 4.2.2 on 2023-06-06 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manageSystem_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderdish',
            options={'ordering': ['order', 'id']},
        ),
        migrations.RemoveField(
            model_name='menu',
            name='dishes',
        ),
        migrations.RemoveField(
            model_name='order',
            name='dishes',
        ),
    ]
